version: '3'
services:
  inferno:
    build:
      context: ./
    environment:
      INFERNO_HOST: "${INFERNO_HOST}"
    volumes:
      - ./data:/opt/inferno/data
    depends_on:
      - validator_service
  validator_service:
    image: infernocommunity/fhir-validator-service:v2.1.0
    # Update this path to match your directory structure
    environment:
      - DISABLE_TX= true
    volumes:
      - ./lib/onc_certification_g10_test_kit/igs:/home/igs
  # fhir_validator_app:
  #   image: infernocommunity/fhir-validator-app
  #   depends_on:
  #     - validator_service
  #   environment:
  #     EXTERNAL_VALIDATOR_URL: http://localhost/validatorapi
  #     VALIDATOR_BASE_PATH: /validator
  nginx:
    image: nginx
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    command: [nginx, '-g', 'daemon off;']
    depends_on: 
      - inferno
  redis:
    image: redis
    volumes:
      - ./data/redis:/data
    command: redis-server --appendonly yes
  worker:
    build:
      context: ./
    environment:
      INFERNO_HOST: "${INFERNO_HOST}"
    volumes:
      - ./data:/opt/inferno/data
    command: bundle exec sidekiq -r ./worker.rb
    depends_on:
      - redis
